# Common configuration for Kitty terminal emulator
paste_actions no-op
enable_audio_bell no
background_opacity 0.95
window_padding_width 10
draw_minimal_borders yes
hide_window_decorations = yes
remember_window_size  no
initial_window_width  1000
initial_window_height 800
startup_session kitty-startup.session

# Include the OS-specific configuration file
include ${KITTY_OS}/kitty.conf